/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { CompressedTexture, Texture, TextureLoader } from "three";
import { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { RigidBody } from "@react-three/rapier";
import { WebGLExtensions } from "three/src/renderers/webgl/WebGLExtensions";
// @ts-ignore
import { KTX2Loader } from "three/examples/jsm/loaders/KTX2Loader";
type GLTFResult = GLTF & {
  nodes: {
    ["2048_Floor_Main"]: THREE.Mesh;
    ["2048_misc_trim"]: THREE.Mesh;
    ["2048_Marble_Door"]: THREE.Mesh;
    ["1024_Fabrics_Outdoor"]: THREE.Mesh;
    ["1024_helipad_balcony_grass"]: THREE.Mesh;
    ["2048_stucco_outside_fix"]: THREE.Mesh;
    ["2048_baseboard_arch"]: THREE.Mesh;
    PBR_black_metal: THREE.Mesh;
    ["2048_Area_rug_couch_table"]: THREE.Mesh;
    ["2048_moulding"]: THREE.Mesh;
    self_illum: THREE.Mesh;
    ["1024_leather_books_logo"]: THREE.Mesh;
    ["1024_Bed"]: THREE.Mesh;
    ["2048_Theater_couch"]: THREE.Mesh;
    ["2048_Firepladce_accsrs"]: THREE.Mesh;
    ["2048_lounge_chair_seat001"]: THREE.Mesh;
    ["2048_Brass_01"]: THREE.Mesh;
    ["2048_outdoor_wood_and_stone"]: THREE.Mesh;
    ["2048_wood_furn_rooftop_patio"]: THREE.Mesh;
    ["2048_ceiling_bed_and_brass"]: THREE.Mesh;
    ["2048_floor_marble_and_trim"]: THREE.Mesh;
    ["2048_wood_panels"]: THREE.Mesh;
    ["2048_edge_med"]: THREE.Mesh;
    ["2048_furniture_misc"]: THREE.Mesh;
    ["2048_Wall_black"]: THREE.Mesh;
    ["2048_Ceiling_and_planter"]: THREE.Mesh;
    ["1024_building_extra"]: THREE.Mesh;
    ["2048_Wall_Main02"]: THREE.Mesh;
    ["2048_edge_sm"]: THREE.Mesh;
    ["2048_Wall_Main01xxxx"]: THREE.Mesh;
    ["2048_Floor_theater_outside_fix"]: THREE.Mesh;
    ["1024_linen_table_orbs_remap"]: THREE.Mesh;
    glow_pink_speaker: THREE.Mesh;
    ["2048_DanceFloor_spa_agave"]: THREE.Mesh;
    record_turning: THREE.Mesh;
    PBR_water: THREE.Mesh;
    PBR_White_Logos: THREE.Mesh;
    PBR_gold: THREE.Mesh;
    PBR_glass_dark: THREE.Mesh;
    PBR_black_logos: THREE.Mesh;
    transparent_stairs: THREE.Mesh;
    heliglass: THREE.Mesh;
    record_below: THREE.Mesh;
    PBR_glass: THREE.Mesh;
    ["2048_black_metal_accsrs_baked_old"]: THREE.Mesh;
    ["1024_helicopter002"]: THREE.Mesh;
    Object004: THREE.Mesh;
    Palm01_Detached01: THREE.Mesh;
    Palm01_Detached02: THREE.Mesh;
    Palm01_Detached03: THREE.Mesh;
    Palm01_Detached04: THREE.Mesh;
    Palm01_Detached05: THREE.Mesh;
    Palm01_Detached06: THREE.Mesh;
    Palm01_Detached07: THREE.Mesh;
    Palm01_Detached08: THREE.Mesh;
    Palm01_Detached09: THREE.Mesh;
    Palm01_Detached10: THREE.Mesh;
    Palm01_Detached11: THREE.Mesh;
    Palm01_Detached12: THREE.Mesh;
    Palm01_Detached13: THREE.Mesh;
    Palm01_Detached14: THREE.Mesh;
    Palm01_Detached15: THREE.Mesh;
    Palm01_Detached16: THREE.Mesh;
    Palm01_Detached17: THREE.Mesh;
    Palm01_Detached18: THREE.Mesh;
    Palm01_Detached19: THREE.Mesh;
    Palm_004_Detached01: THREE.Mesh;
    Palm_004_Detached02: THREE.Mesh;
    Palm_004_Detached03: THREE.Mesh;
    Palm_004_Detached04: THREE.Mesh;
    Palm_004_Detached05: THREE.Mesh;
    Palm_004_Detached06: THREE.Mesh;
    Palm_004_Detached07: THREE.Mesh;
    Palm_004_Detached08: THREE.Mesh;
    Palm_004_Detached09: THREE.Mesh;
    Palm_004_Detached10: THREE.Mesh;
    Palm_004_Detached11: THREE.Mesh;
    Palm_004_Detached12: THREE.Mesh;
    Palm_004_Detached13: THREE.Mesh;
    Palm_004_Detached14: THREE.Mesh;
    Palm_004_Detached15: THREE.Mesh;
    Palm_004_Detached16: THREE.Mesh;
    Palm_004_Detached17: THREE.Mesh;
    Palm_004_Detached018: THREE.Mesh;
    Palm_004_Detached019: THREE.Mesh;
    Palm_004_Detached020: THREE.Mesh;
    Palm_004_Detached021: THREE.Mesh;
    Palm_004_Detached022: THREE.Mesh;
    Palm_004_Detached023: THREE.Mesh;
    Palm_004_Detached024: THREE.Mesh;
    Palm_004_Detached025: THREE.Mesh;
    Palm_004_Detached026: THREE.Mesh;
    Palm_004_Detached027: THREE.Mesh;
    Palm_004_Detached028: THREE.Mesh;
    Palm_004_Detached029: THREE.Mesh;
    Palm_004_Detached030: THREE.Mesh;
    Palm_004_Detached031: THREE.Mesh;
    Palm_004_Detached032: THREE.Mesh;
    Palm_004_Detached033: THREE.Mesh;
    Palm_004_Detached034: THREE.Mesh;
    Palm_3_Detached01: THREE.Mesh;
    Palm_3_Detached02: THREE.Mesh;
    Palm_3_Detached03: THREE.Mesh;
    Palm_3_Detached04: THREE.Mesh;
    Palm_3_Detached05: THREE.Mesh;
    Palm_3_Detached06: THREE.Mesh;
    Palm_3_Detached07: THREE.Mesh;
    Palm_3_Detached08: THREE.Mesh;
    Palm_3_Detached09: THREE.Mesh;
    Palm_3_Detached10: THREE.Mesh;
    Palm_3_Detached11: THREE.Mesh;
    Palm_3_Detached12: THREE.Mesh;
    Palm_3_Detached13: THREE.Mesh;
    Palm_3_Detached14: THREE.Mesh;
    Palm_3_Detached15: THREE.Mesh;
    Palm_3_Detached16: THREE.Mesh;
    Palm_3_Detached17: THREE.Mesh;
    Palm_3_Detached018: THREE.Mesh;
    Palm_3_Detached019: THREE.Mesh;
    Palm_3_Detached020: THREE.Mesh;
    Palm_3_Detached021: THREE.Mesh;
    Palm_3_Detached022: THREE.Mesh;
    Palm_3_Detached023: THREE.Mesh;
    Palm_3_Detached024: THREE.Mesh;
    Palm_3_Detached025: THREE.Mesh;
    Palm_3_Detached026: THREE.Mesh;
    Palm_3_Detached027: THREE.Mesh;
    Palm_3_Detached028: THREE.Mesh;
    Palm_3_Detached029: THREE.Mesh;
    Palm_3_Detached030: THREE.Mesh;
    Palm_3_Detached031: THREE.Mesh;
    Palm_3_Detached032: THREE.Mesh;
    Palm_3_Detached033: THREE.Mesh;
    Palm_3_Detached034: THREE.Mesh;
    ["2048_ceiling_and_roof_djbooth"]: THREE.Mesh;
    ["2048_RecordPlayer__books_dj"]: THREE.Mesh;
    ["water-nocollider"]: THREE.Mesh;
  };
  materials: {
    ["2048_Floor Main"]: THREE.MeshBasicMaterial;
    ["2048_misc trim"]: THREE.MeshBasicMaterial;
    ["2048_Marble Door"]: THREE.MeshBasicMaterial;
    ["1024_Fabrics Outdoor"]: THREE.MeshBasicMaterial;
    ["1024_helipad_balcony_grass"]: THREE.MeshBasicMaterial;
    ["2048_stucco outside fix"]: THREE.MeshBasicMaterial;
    ["2048_baseboard arch"]: THREE.MeshBasicMaterial;
    ["Metal Black Physical"]: THREE.MeshStandardMaterial;
    ["2048_Area rug couch table"]: THREE.MeshBasicMaterial;
    ["2048_moulding"]: THREE.MeshBasicMaterial;
    ["PBR Emissive"]: THREE.MeshStandardMaterial;
    ["2048_leather_books_"]: THREE.MeshBasicMaterial;
    ["1024_Bed"]: THREE.MeshBasicMaterial;
    ["2048_Theater couch"]: THREE.MeshBasicMaterial;
    ["2048_Firepladce accsrs"]: THREE.MeshBasicMaterial;
    ["2048_lounge_chair_seat001"]: THREE.MeshBasicMaterial;
    ["2048_Brass 01"]: THREE.MeshBasicMaterial;
    ["2048_outdoor_wood and stone"]: THREE.MeshBasicMaterial;
    ["2048_wood furn rooftop patio"]: THREE.MeshBasicMaterial;
    ["2048_ceiling bed and brass"]: THREE.MeshBasicMaterial;
    ["2048_floor marble and trim"]: THREE.MeshBasicMaterial;
    ["2048_wood panels"]: THREE.MeshBasicMaterial;
    ["2048_edge_med"]: THREE.MeshBasicMaterial;
    ["2048_furniture misc"]: THREE.MeshBasicMaterial;
    ["2048_Wall black"]: THREE.MeshBasicMaterial;
    ["2048_Ceiling and planter"]: THREE.MeshBasicMaterial;
    ["1024 building extra"]: THREE.MeshBasicMaterial;
    ["2048_Wall Main02"]: THREE.MeshBasicMaterial;
    ["2048_edge smx"]: THREE.MeshBasicMaterial;
    ["2048_Wall Main01xxxx"]: THREE.MeshBasicMaterial;
    ["2048_Floor theater outside"]: THREE.MeshBasicMaterial;
    ["1024_linen_table_orbs remap"]: THREE.MeshBasicMaterial;
    ["PBR emissive pink"]: THREE.MeshStandardMaterial;
    ["2048_DanceFloor_spa_agave"]: THREE.MeshBasicMaterial;
    ["2048_RecordPlayer_ books_dj"]: THREE.MeshBasicMaterial;
    Water: THREE.MeshStandardMaterial;
    ["PBR Glossy White"]: THREE.MeshStandardMaterial;
    ["PBR Gold"]: THREE.MeshStandardMaterial;
    ["Glass Physical"]: THREE.MeshStandardMaterial;
    ["PBR Glossy Black"]: THREE.MeshStandardMaterial;
    ["transparent disk"]: THREE.MeshBasicMaterial;
    ["2048_black metal accsrs baked"]: THREE.MeshBasicMaterial;
    ["2048_helicopter002"]: THREE.MeshBasicMaterial;
    ["palmtree Trunk"]: THREE.MeshBasicMaterial;
    palmtree: THREE.MeshBasicMaterial;
    ["2048_ceiling and roof"]: THREE.MeshBasicMaterial;
    ["Jacuzzi Water"]: THREE.MeshStandardMaterial;
  };
};
const KTX_CDN = "https://cdn.jsdelivr.net/gh/pmndrs/drei-assets@master/basis/";

const textureLoader = new TextureLoader();
let ktx2loader: KTX2Loader | undefined;

// it's inconvenient to have to produce a gl object to check for ktx2 support, especially when it comes to the cache keys
// solution is to create a skeleton object that provides the minimum requirements to check for ktx support, defined below
// https://github.com/mrdoob/three.js/blob/master/examples/jsm/loaders/KTX2Loader.js#L113-L135
type PotentialCanvas = WebGLRenderingContext | WebGL2RenderingContext | null;
type KTXSupportCheck = {
  capabilities: { isWebGL2: boolean };
  extensions: WebGLExtensions;
};

const setupKtx2 = () => {
  if (ktx2loader) return;

  ktx2loader = new KTX2Loader();
  ktx2loader.setTranscoderPath(KTX_CDN);

  let supportsWebgl2: boolean;
  const el = document.createElement("canvas");
  let gl: PotentialCanvas = el.getContext("webgl2");
  if (gl) {
    supportsWebgl2 = true;
  } else {
    gl = el.getContext("webgl");
    supportsWebgl2 = false;
  }
  if (!gl) {
    throw new Error("No WebGL support");
  }
  el.remove();
  const minimumGL: KTXSupportCheck = {
    extensions: new WebGLExtensions(gl),
    capabilities: { isWebGL2: supportsWebgl2 },
  };

  // @ts-ignore
  ktx2loader.detectSupport(minimumGL);
};

function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(
    "/PENTHOUSE_Quartz-v1-v3.glb",
    true,
    true,
    (loader) => {
      setupKtx2();
      loader.setKTX2Loader(ktx2loader!);
    }
  ) as any;
  const { actions } = useAnimations(animations, group);
  return (
    <RigidBody colliders="trimesh" type="fixed">
      <group ref={group} {...props} dispose={null} position={[1, -20, -7.9]}>
        <group>
          <mesh
            name="2048_Floor_Main"
            castShadow
            receiveShadow
            geometry={nodes["2048_Floor_Main"].geometry}
            material={materials["2048_Floor Main"]}
            position={[-1.834, 0, 9.919]}
          />
          <mesh
            name="2048_misc_trim"
            castShadow
            receiveShadow
            geometry={nodes["2048_misc_trim"].geometry}
            material={materials["2048_misc trim"]}
            position={[-6.685, 5.791, 16.867]}
          />
          <mesh
            name="2048_Marble_Door"
            castShadow
            receiveShadow
            geometry={nodes["2048_Marble_Door"].geometry}
            material={materials["2048_Marble Door"]}
            position={[8.823, 0, 21.041]}
          />
          <mesh
            name="1024_Fabrics_Outdoor"
            castShadow
            receiveShadow
            geometry={nodes["1024_Fabrics_Outdoor"].geometry}
            material={materials["1024_Fabrics Outdoor"]}
            position={[-26.162, 0.308, -7.251]}
            rotation={[-Math.PI, 1.222, -Math.PI]}
          />
          <mesh
            name="1024_helipad_balcony_grass"
            castShadow
            receiveShadow
            geometry={nodes["1024_helipad_balcony_grass"].geometry}
            material={materials["1024_helipad_balcony_grass"]}
            position={[-21.591, -0.102, 14.63]}
            rotation={[0, Math.PI / 4, 0]}
          />
          <mesh
            name="2048_stucco_outside_fix"
            castShadow
            receiveShadow
            geometry={nodes["2048_stucco_outside_fix"].geometry}
            material={materials["2048_stucco outside fix"]}
            position={[-9.655, -0.102, 21.925]}
          />
          <mesh
            name="2048_baseboard_arch"
            castShadow
            receiveShadow
            geometry={nodes["2048_baseboard_arch"].geometry}
            material={materials["2048_baseboard arch"]}
            position={[-8.905, 3.179, 11.746]}
            rotation={[0, 1.57, 0]}
            scale={[0.665, 1, 0.903]}
          />
          <mesh
            name="PBR_black_metal"
            castShadow
            receiveShadow
            geometry={nodes.PBR_black_metal.geometry}
            material={materials["Metal Black Physical"]}
            position={[-11.338, 7.428, 2.699]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.19}
          />
          <mesh
            name="2048_Area_rug_couch_table"
            castShadow
            receiveShadow
            geometry={nodes["2048_Area_rug_couch_table"].geometry}
            material={materials["2048_Area rug couch table"]}
            position={[-11.897, 0.028, 16.734]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={1.25}
          />
          <mesh
            name="2048_moulding"
            castShadow
            receiveShadow
            geometry={nodes["2048_moulding"].geometry}
            material={materials["2048_moulding"]}
            position={[-16.183, 4.652, 8.344]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            name="self_illum"
            castShadow
            receiveShadow
            geometry={nodes.self_illum.geometry}
            material={materials["PBR Emissive"]}
            position={[3.73, 2.256, 13.605]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={2.335}
          />
          <mesh
            name="1024_leather_books_logo"
            castShadow
            receiveShadow
            geometry={nodes["1024_leather_books_logo"].geometry}
            material={materials["2048_leather_books_"]}
            position={[0.597, 0.733, 17.797]}
            rotation={[0, -Math.PI / 3, 0]}
          />
          <mesh
            name="1024_Bed"
            castShadow
            receiveShadow
            geometry={nodes["1024_Bed"].geometry}
            material={materials["1024_Bed"]}
            position={[-11.147, 0.264, 1.915]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={[1.01, 1.099, 1.189]}
          />
          <mesh
            name="2048_Theater_couch"
            castShadow
            receiveShadow
            geometry={nodes["2048_Theater_couch"].geometry}
            material={materials["2048_Theater couch"]}
            position={[8.747, 0.019, 16.791]}
            rotation={[-Math.PI, 0, 0]}
            scale={[1, -1, 1]}
          />
          <mesh
            name="2048_Firepladce_accsrs"
            castShadow
            receiveShadow
            geometry={nodes["2048_Firepladce_accsrs"].geometry}
            material={materials["2048_Firepladce accsrs"]}
            position={[-6.42, 0.762, 10.899]}
            rotation={[Math.PI / 2, 0, -Math.PI]}
            scale={[0.905, 1, 1]}
          />
          <mesh
            name="2048_lounge_chair_seat001"
            castShadow
            receiveShadow
            geometry={nodes["2048_lounge_chair_seat001"].geometry}
            material={materials["2048_lounge_chair_seat001"]}
            position={[-8.833, 0.391, 16.948]}
            rotation={[Math.PI / 2, 0, 1.658]}
            scale={1.271}
          />
          <mesh
            name="2048_Brass_01"
            castShadow
            receiveShadow
            geometry={nodes["2048_Brass_01"].geometry}
            material={materials["2048_Brass 01"]}
            position={[-9.766, 0, 19.087]}
            rotation={[Math.PI / 2, 0, 0.175]}
          />
          <mesh
            name="2048_outdoor_wood_and_stone"
            castShadow
            receiveShadow
            geometry={nodes["2048_outdoor_wood_and_stone"].geometry}
            material={materials["2048_outdoor_wood and stone"]}
            position={[-11.31, -0.102, 30.68]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            name="2048_wood_furn_rooftop_patio"
            castShadow
            receiveShadow
            geometry={nodes["2048_wood_furn_rooftop_patio"].geometry}
            material={materials["2048_wood furn rooftop patio"]}
            position={[-15.584, 6.287, 3.442]}
            rotation={[-Math.PI, 0, -Math.PI]}
          />
          <mesh
            name="2048_ceiling_bed_and_brass"
            castShadow
            receiveShadow
            geometry={nodes["2048_ceiling_bed_and_brass"].geometry}
            material={materials["2048_ceiling bed and brass"]}
            position={[-11.167, 5.029, 6.852]}
          />
          <mesh
            name="2048_floor_marble_and_trim"
            castShadow
            receiveShadow
            geometry={nodes["2048_floor_marble_and_trim"].geometry}
            material={materials["2048_floor marble and trim"]}
            position={[-11.167, 0.102, 2.174]}
          />
          <mesh
            name="2048_wood_panels"
            castShadow
            receiveShadow
            geometry={nodes["2048_wood_panels"].geometry}
            material={materials["2048_wood panels"]}
            position={[14.042, 2.815, 19.952]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
          />
          <mesh
            name="2048_edge_med"
            castShadow
            receiveShadow
            geometry={nodes["2048_edge_med"].geometry}
            material={materials["2048_edge_med"]}
            position={[11.577, 0, 20.07]}
          />
          <mesh
            name="2048_furniture_misc"
            castShadow
            receiveShadow
            geometry={nodes["2048_furniture_misc"].geometry}
            material={materials["2048_furniture misc"]}
            position={[-14.049, 0.057, 18.144]}
            rotation={[Math.PI / 2, 0, 1.833]}
          />
          <mesh
            name="2048_Wall_black"
            castShadow
            receiveShadow
            geometry={nodes["2048_Wall_black"].geometry}
            material={materials["2048_Wall black"]}
            position={[11.577, 0, 20.07]}
          />
          <mesh
            name="2048_Ceiling_and_planter"
            castShadow
            receiveShadow
            geometry={nodes["2048_Ceiling_and_planter"].geometry}
            material={materials["2048_Ceiling and planter"]}
            position={[-5.805, 5.486, 18.136]}
          />
          <mesh
            name="1024_building_extra"
            castShadow
            receiveShadow
            geometry={nodes["1024_building_extra"].geometry}
            material={materials["1024 building extra"]}
            position={[-21.422, -7.21, 8.865]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            name="2048_Wall_Main02"
            castShadow
            receiveShadow
            geometry={nodes["2048_Wall_Main02"].geometry}
            material={materials["2048_Wall Main02"]}
            position={[11.577, 0, 20.07]}
          />
          <mesh
            name="2048_edge_sm"
            castShadow
            receiveShadow
            geometry={nodes["2048_edge_sm"].geometry}
            material={materials["2048_edge smx"]}
            position={[16.196, 4.877, 15.881]}
          />
          <mesh
            name="2048_Wall_Main01xxxx"
            castShadow
            receiveShadow
            geometry={nodes["2048_Wall_Main01xxxx"].geometry}
            material={materials["2048_Wall Main01xxxx"]}
            position={[11.577, 0, 20.07]}
          />
          <mesh
            name="2048_Floor_theater_outside_fix"
            castShadow
            receiveShadow
            geometry={nodes["2048_Floor_theater_outside_fix"].geometry}
            material={materials["2048_Floor theater outside"]}
            position={[8.529, 0, 14.082]}
          />
          <mesh
            name="1024_linen_table_orbs_remap"
            castShadow
            receiveShadow
            geometry={nodes["1024_linen_table_orbs_remap"].geometry}
            material={materials["1024_linen_table_orbs remap"]}
            position={[-6.49, 3.086, 49.974]}
            rotation={[0, 1.57, 0]}
          />
          <mesh
            name="glow_pink_speaker"
            castShadow
            receiveShadow
            geometry={nodes.glow_pink_speaker.geometry}
            material={materials["PBR emissive pink"]}
            position={[-5.55, 7.065, 15.443]}
            rotation={[0.988, -0.715, 0.783]}
            scale={1.43}
          />
          <mesh
            name="2048_DanceFloor_spa_agave"
            castShadow
            receiveShadow
            geometry={nodes["2048_DanceFloor_spa_agave"].geometry}
            material={materials["2048_DanceFloor_spa_agave"]}
            position={[-10.359, 6.635, 17.228]}
            scale={[0.811, 1, 0.811]}
          />
          <mesh
            name="record_turning"
            castShadow
            receiveShadow
            geometry={nodes.record_turning.geometry}
            material={materials["2048_RecordPlayer_ books_dj"]}
            position={[-7.331, 0.996, 12.337]}
            scale={[1.696, 1.732, 1.696]}
          />
          <mesh
            name="PBR_water"
            castShadow
            receiveShadow
            geometry={nodes.PBR_water.geometry}
            material={materials.Water}
            position={[0.333, 0, 21.034]}
          />
          <mesh
            name="PBR_White_Logos"
            castShadow
            receiveShadow
            geometry={nodes.PBR_White_Logos.geometry}
            material={materials["PBR Glossy White"]}
            position={[3.642, 2.855, 10.377]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[5.402, 1.39, 5.402]}
          />
          <mesh
            name="PBR_gold"
            castShadow
            receiveShadow
            geometry={nodes.PBR_gold.geometry}
            material={materials["PBR Gold"]}
            position={[-0.95, 1.12, 18.632]}
            rotation={[Math.PI / 2, 0, 0]}
          />
          <mesh
            name="PBR_glass_dark"
            castShadow
            receiveShadow
            geometry={nodes.PBR_glass_dark.geometry}
            material={materials["Glass Physical"]}
            position={[-3.867, 3.887, 23.635]}
            rotation={[0, 1.57, 0]}
          />
          <mesh
            name="PBR_black_logos"
            castShadow
            receiveShadow
            geometry={nodes.PBR_black_logos.geometry}
            material={materials["PBR Glossy Black"]}
            position={[3.642, 2.855, 10.377]}
            rotation={[Math.PI / 2, 0, -Math.PI / 2]}
            scale={[5.402, 1.39, 5.402]}
          />
          <mesh
            name="transparent_stairs"
            castShadow
            receiveShadow
            geometry={nodes.transparent_stairs.geometry}
            material={materials["transparent disk"]}
            position={[-18.347, 3.41, 15.804]}
            rotation={[Math.PI / 2, 0, Math.PI / 2]}
          />
          <mesh
            name="heliglass"
            castShadow
            receiveShadow
            geometry={nodes.heliglass.geometry}
            material={materials["PBR Glossy Black"]}
            position={[-3.867, 3.887, 23.635]}
            rotation={[0, 1.57, 0]}
          />
          <mesh
            name="record_below"
            castShadow
            receiveShadow
            geometry={nodes.record_below.geometry}
            material={materials["PBR Gold"]}
            position={[-7.331, 0.952, 12.337]}
            scale={1.732}
          />
          <mesh
            name="PBR_glass"
            castShadow
            receiveShadow
            geometry={nodes.PBR_glass.geometry}
            material={materials["Glass Physical"]}
            position={[-3.115, 0, 13.939]}
          />
          <mesh
            name="2048_black_metal_accsrs_baked_old"
            castShadow
            receiveShadow
            geometry={nodes["2048_black_metal_accsrs_baked_old"].geometry}
            material={materials["2048_black metal accsrs baked"]}
            position={[4.898, -0.102, 21.727]}
          />
          <mesh
            name="1024_helicopter002"
            castShadow
            receiveShadow
            geometry={nodes["1024_helicopter002"].geometry}
            material={materials["2048_helicopter002"]}
            position={[9.372, 1.383, 28.041]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            name="Object004"
            castShadow
            receiveShadow
            geometry={nodes.Object004.geometry}
            material={materials["2048_helicopter002"]}
            position={[9.372, 1.383, 28.041]}
            rotation={[Math.PI, 0, Math.PI]}
          />
          <mesh
            name="Palm01_Detached01"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached01.geometry}
            material={materials["palmtree Trunk"]}
            position={[-7.495, 9.893, 3.487]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached02"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached02.geometry}
            material={materials.palmtree}
            position={[-8.101, 13.6, 3.132]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached03"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached03.geometry}
            material={materials.palmtree}
            position={[-8.205, 13.506, 4.283]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached04"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached04.geometry}
            material={materials.palmtree}
            position={[-8.194, 13.08, 2.692]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached05"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached05.geometry}
            material={materials.palmtree}
            position={[-7.031, 13.575, 3.833]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached06"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached06.geometry}
            material={materials.palmtree}
            position={[-8.827, 13.412, 3.6]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached07"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached07.geometry}
            material={materials.palmtree}
            position={[-8.444, 13.573, 3.574]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached08"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached08.geometry}
            material={materials.palmtree}
            position={[-7.192, 13.199, 4.388]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached09"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached09.geometry}
            material={materials.palmtree}
            position={[-8.874, 12.901, 3.026]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached10"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached10.geometry}
            material={materials.palmtree}
            position={[-7.065, 13.432, 2.618]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached11"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached11.geometry}
            material={materials.palmtree}
            position={[-8.505, 13.235, 4.574]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached12"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached12.geometry}
            material={materials.palmtree}
            position={[-8.273, 12.732, 4.022]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached13"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached13.geometry}
            material={materials.palmtree}
            position={[-8.417, 12.713, 3.073]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached14"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached14.geometry}
            material={materials.palmtree}
            position={[-7.63, 12.513, 2.986]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached15"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached15.geometry}
            material={materials.palmtree}
            position={[-7.711, 12.352, 4.103]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached16"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached16.geometry}
            material={materials.palmtree}
            position={[-8.664, 12.732, 3.547]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached17"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached17.geometry}
            material={materials.palmtree}
            position={[-7.561, 12.711, 2.853]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached18"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached18.geometry}
            material={materials.palmtree}
            position={[-7.071, 12.491, 3.761]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm01_Detached19"
            castShadow
            receiveShadow
            geometry={nodes.Palm01_Detached19.geometry}
            material={materials.palmtree}
            position={[-8.431, 12.331, 4.321]}
            rotation={[Math.PI / 2, 0, 0]}
            scale={7.445}
          />
          <mesh
            name="Palm_004_Detached01"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached01.geometry}
            material={materials["palmtree Trunk"]}
            position={[-14.967, 10.035, 3.385]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached02"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached02.geometry}
            material={materials.palmtree}
            position={[-14.862, 13.889, 4.142]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached03"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached03.geometry}
            material={materials.palmtree}
            position={[-14.232, 13.833, 3.4]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached04"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached04.geometry}
            material={materials.palmtree}
            position={[-15.754, 13.216, 3.112]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached05"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached05.geometry}
            material={materials.palmtree}
            position={[-14.932, 13.826, 2.997]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached06"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached06.geometry}
            material={materials.palmtree}
            position={[-16.028, 13.712, 3.781]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached07"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached07.geometry}
            material={materials.palmtree}
            position={[-14.049, 13.689, 3.17]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached08"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached08.geometry}
            material={materials.palmtree}
            position={[-14.821, 13.647, 4.403]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached09"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached09.geometry}
            material={materials.palmtree}
            position={[-15.438, 13.68, 2.554]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached10"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached10.geometry}
            material={materials.palmtree}
            position={[-15.206, 13.285, 3.024]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached11"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached11.geometry}
            material={materials.palmtree}
            position={[-14.382, 13.011, 3.66]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached12"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached12.geometry}
            material={materials.palmtree}
            position={[-14.909, 13.226, 4.32]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached13"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached13.geometry}
            material={materials.palmtree}
            position={[-15.79, 12.896, 3.367]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached14"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached14.geometry}
            material={materials.palmtree}
            position={[-15.716, 13.261, 3.241]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached15"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached15.geometry}
            material={materials.palmtree}
            position={[-14.663, 12.907, 2.676]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached16"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached16.geometry}
            material={materials.palmtree}
            position={[-14.13, 13.186, 3.894]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached17"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached17.geometry}
            material={materials.palmtree}
            position={[-15.755, 12.776, 4.107]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached018"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached018.geometry}
            material={materials["palmtree Trunk"]}
            position={[2.636, 10.035, 7.026]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached019"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached019.geometry}
            material={materials.palmtree}
            position={[2.741, 13.889, 7.783]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached020"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached020.geometry}
            material={materials.palmtree}
            position={[3.371, 13.833, 7.041]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached021"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached021.geometry}
            material={materials.palmtree}
            position={[1.849, 13.216, 6.753]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached022"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached022.geometry}
            material={materials.palmtree}
            position={[2.671, 13.826, 6.638]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached023"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached023.geometry}
            material={materials.palmtree}
            position={[1.574, 13.712, 7.422]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached024"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached024.geometry}
            material={materials.palmtree}
            position={[3.554, 13.689, 6.811]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached025"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached025.geometry}
            material={materials.palmtree}
            position={[2.782, 13.647, 8.045]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached026"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached026.geometry}
            material={materials.palmtree}
            position={[2.164, 13.68, 6.195]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached027"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached027.geometry}
            material={materials.palmtree}
            position={[2.397, 13.285, 6.666]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached028"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached028.geometry}
            material={materials.palmtree}
            position={[3.221, 13.011, 7.301]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached029"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached029.geometry}
            material={materials.palmtree}
            position={[2.693, 13.226, 7.961]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached030"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached030.geometry}
            material={materials.palmtree}
            position={[1.812, 12.896, 7.008]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached031"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached031.geometry}
            material={materials.palmtree}
            position={[1.887, 13.261, 6.882]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached032"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached032.geometry}
            material={materials.palmtree}
            position={[2.94, 12.907, 6.317]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached033"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached033.geometry}
            material={materials.palmtree}
            position={[3.472, 13.186, 7.536]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_004_Detached034"
            castShadow
            receiveShadow
            geometry={nodes.Palm_004_Detached034.geometry}
            material={materials.palmtree}
            position={[1.848, 12.776, 7.748]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached01"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached01.geometry}
            material={materials["palmtree Trunk"]}
            position={[2.521, 10.476, 17.588]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached02"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached02.geometry}
            material={materials.palmtree}
            position={[2.488, 14.83, 18.096]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached03"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached03.geometry}
            material={materials.palmtree}
            position={[3.551, 14.768, 17.919]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached04"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached04.geometry}
            material={materials.palmtree}
            position={[2.325, 14.07, 16.492]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached05"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached05.geometry}
            material={materials.palmtree}
            position={[3.096, 14.759, 16.963]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached06"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached06.geometry}
            material={materials.palmtree}
            position={[1.621, 14.63, 17.008]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached07"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached07.geometry}
            material={materials.palmtree}
            position={[3.924, 14.605, 17.755]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached08"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached08.geometry}
            material={materials.palmtree}
            position={[2.294, 14.557, 18.355]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached09"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached09.geometry}
            material={materials.palmtree}
            position={[2.851, 14.594, 16.13]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached10"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached10.geometry}
            material={materials.palmtree}
            position={[3.049, 14.148, 16.896]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached11"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached11.geometry}
            material={materials.palmtree}
            position={[2.969, 13.838, 18.069]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached12"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached12.geometry}
            material={materials.palmtree}
            position={[2.067, 14.082, 18.067]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached13"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached13.geometry}
            material={materials.palmtree}
            position={[2.476, 13.709, 16.617]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached14"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached14.geometry}
            material={materials.palmtree}
            position={[2.515, 14.121, 16.608]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached15"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached15.geometry}
            material={materials.palmtree}
            position={[3.739, 13.721, 17.24]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached16"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached16.geometry}
            material={materials.palmtree}
            position={[2.997, 14.036, 18.416]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached17"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached17.geometry}
            material={materials.palmtree}
            position={[1.612, 13.573, 17.204]}
            rotation={[Math.PI / 2, 0, 0.314]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached018"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached018.geometry}
            material={materials["palmtree Trunk"]}
            position={[-20.529, 3.837, 29.939]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached019"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached019.geometry}
            material={materials.palmtree}
            position={[-20.811, 8.192, 30.362]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached020"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached020.geometry}
            material={materials.palmtree}
            position={[-19.801, 8.129, 30.74]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached021"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached021.geometry}
            material={materials.palmtree}
            position={[-20.15, 7.432, 28.892]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached022"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached022.geometry}
            material={materials.palmtree}
            position={[-19.718, 8.121, 29.685]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached023"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached023.geometry}
            material={materials.palmtree}
            position={[-21.018, 7.992, 28.987]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached024"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached024.geometry}
            material={materials.palmtree}
            position={[-19.397, 7.967, 30.784]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached025"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached025.geometry}
            material={materials.palmtree}
            position={[-21.108, 7.919, 30.489]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached026"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached026.geometry}
            material={materials.palmtree}
            position={[-19.513, 7.956, 28.841]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached027"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached027.geometry}
            material={materials.palmtree}
            position={[-19.725, 7.51, 29.603]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached028"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached028.geometry}
            material={materials.palmtree}
            position={[-20.381, 7.2, 30.58]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached029"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached029.geometry}
            material={materials.palmtree}
            position={[-21.161, 7.443, 30.127]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached030"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached030.geometry}
            material={materials.palmtree}
            position={[-20.081, 7.071, 29.076]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached031"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached031.geometry}
            material={materials.palmtree}
            position={[-20.043, 7.483, 29.087]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached032"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached032.geometry}
            material={materials.palmtree}
            position={[-19.299, 7.083, 30.247]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached033"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached033.geometry}
            material={materials.palmtree}
            position={[-20.53, 7.398, 30.894]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="Palm_3_Detached034"
            castShadow
            receiveShadow
            geometry={nodes.Palm_3_Detached034.geometry}
            material={materials.palmtree}
            position={[-21.123, 6.935, 29.152]}
            rotation={[Math.PI / 2, 0, 0.838]}
            scale={9.462}
          />
          <mesh
            name="2048_ceiling_and_roof_djbooth"
            castShadow
            receiveShadow
            geometry={nodes["2048_ceiling_and_roof_djbooth"].geometry}
            material={materials["2048_ceiling and roof"]}
            position={[-0.478, 4.958, 19.24]}
          />
          <mesh
            name="2048_RecordPlayer__books_dj"
            castShadow
            receiveShadow
            geometry={nodes["2048_RecordPlayer__books_dj"].geometry}
            material={materials["2048_RecordPlayer_ books_dj"]}
            position={[-7.331, 0.996, 12.337]}
            scale={[1.696, 1.732, 1.696]}
          />
          <mesh
            name="water-nocollider"
            castShadow
            receiveShadow
            geometry={nodes["water-nocollider"].geometry}
            material={materials["Jacuzzi Water"]}
            position={[-13.521, 6.713, 9.258]}
          />
        </group>
      </group>
    </RigidBody>
  );
}

useGLTF.preload("/PENTHOUSE_Quartz-v1-v3.glb", true, false, (loader) => {
  setupKtx2();
  loader.setKTX2Loader(ktx2loader!);
});

export default Model;
